flaskCounterVersion: 0.1
mysqlVersion: 8.0
ingressEnabled: true

### Deployment
replicaCount: 1

resources:
  limits:
    cpu: "0.6"
    memory: "200Mi"
  requests:
    cpu: "0.3"
    memory: "100Mi"

### StatefulSet
resources:
  limits:
    cpu: "0.6"
    memory: "1000Mi"
  requests:
    cpu: "0.3"
    memory: "500Mi"

### HPA
maxReplicas: 6
minReplicas: 1


### Ingress
ingressPort: 80